directories:
  output: dist
  buildResources: build
appId: com.tuempresa.sandbox
productName: SandBox
files:
  - filter:
      - app/**/*
      - main.js
      - preload.js
      - package.json
nsis:
  oneClick: false
  perMachine: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: always
  createStartMenuShortcut: true
  include: build/installer.nsh
win:
  icon: app/img/app-logo.ico
electronVersion: 26.6.10
